//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPK_WysylkaXML.UI.Components.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPK_WysylkaXML.UI.Components.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załadowane moduły: \n{0}.
        /// </summary>
        public static string ApplicationVersionPopup_LoadedModulesLabel {
            get {
                return ResourceManager.GetString("ApplicationVersionPopup_LoadedModulesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja głównego modułu: {0}.
        /// </summary>
        public static string ApplicationVersionPopup_MainModuleVersionLabel {
            get {
                return ResourceManager.GetString("ApplicationVersionPopup_MainModuleVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja aplikacji.
        /// </summary>
        public static string ApplicationVersionPopup_Title {
            get {
                return ResourceManager.GetString("ApplicationVersionPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły błędu: {0}.
        /// </summary>
        public static string Common_ApplicationErrorDetails {
            get {
                return ResourceManager.GetString("Common_ApplicationErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd w trakcie uruchamiania aplikacji.
        /// </summary>
        public static string Common_ApplicationErrorMessage {
            get {
                return ResourceManager.GetString("Common_ApplicationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd aplikacji.
        /// </summary>
        public static string Common_ApplicationErrorTitle {
            get {
                return ResourceManager.GetString("Common_ApplicationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Common_BtnCancelText {
            get {
                return ResourceManager.GetString("Common_BtnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Common_BtnSaveText {
            get {
                return ResourceManager.GetString("Common_BtnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string Common_CloseBtn {
            get {
                return ResourceManager.GetString("Common_CloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd tworzenia katalogu.
        /// </summary>
        public static string Common_CreateFolderTitle {
            get {
                return ResourceManager.GetString("Common_CreateFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagany jest katalog {0}, gdzie przechowywane będą pliki licencji.
        /// </summary>
        public static string Common_CreateLicenseFolderDetails {
            get {
                return ResourceManager.GetString("Common_CreateLicenseFolderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się utworzyć folderu licencji..
        /// </summary>
        public static string Common_CreateLicenseFolderMessage {
            get {
                return ResourceManager.GetString("Common_CreateLicenseFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę skontaktować się z IT w celu naprawienia błędu. Potrzebny katalog: {0}.
        /// </summary>
        public static string Common_CreateLogFolderDetails {
            get {
                return ResourceManager.GetString("Common_CreateLogFolderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się utworzyć folderu do przechowywania logów..
        /// </summary>
        public static string Common_CreateLogFolderMessage {
            get {
                return ResourceManager.GetString("Common_CreateLogFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W celu aktywacji pełnej wersji należy wgrać plik licencji do podkatalogu License.
        /// </summary>
        public static string Common_MissingLicenseDetails {
            get {
                return ResourceManager.GetString("Common_MissingLicenseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak licencji, aplikacja działa w trybie demo.
        /// </summary>
        public static string Common_MissingLicenseMessage {
            get {
                return ResourceManager.GetString("Common_MissingLicenseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak licencji.
        /// </summary>
        public static string Common_MissingLicenseTitle {
            get {
                return ResourceManager.GetString("Common_MissingLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę skontaktować się z IT w celu naprawienia błędu. Katalog danych: {0}.
        /// </summary>
        public static string Common_WritePermissionsDetails {
            get {
                return ResourceManager.GetString("Common_WritePermissionsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak możliwości zapisu w katalogu danych..
        /// </summary>
        public static string Common_WritePermissionsMessage {
            get {
                return ResourceManager.GetString("Common_WritePermissionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd zapisu.
        /// </summary>
        public static string Common_WritePermissionsTitle {
            get {
                return ResourceManager.GetString("Common_WritePermissionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń wszystkie wiersze.
        /// </summary>
        public static string EditJPKView_DeleteAllRowsBtn {
            get {
                return ResourceManager.GetString("EditJPKView_DeleteAllRowsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zaznaczony wiersz.
        /// </summary>
        public static string EditJPKView_DeleteSelectedRowBtn {
            get {
                return ResourceManager.GetString("EditJPKView_DeleteSelectedRowBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import wierszy.
        /// </summary>
        public static string EditJPKView_ImportRowsBtn {
            get {
                return ResourceManager.GetString("EditJPKView_ImportRowsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy wiersza zakupu.
        /// </summary>
        public static string EditJPKView_NewPurchaseRowBtn {
            get {
                return ResourceManager.GetString("EditJPKView_NewPurchaseRowBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy wiersz sprzedaży.
        /// </summary>
        public static string EditJPKView_NewSaleRowBtn {
            get {
                return ResourceManager.GetString("EditJPKView_NewSaleRowBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string HistoryView_DescriptionHeader {
            get {
                return ResourceManager.GetString("HistoryView_DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wysyłki od:.
        /// </summary>
        public static string HistoryView_FromDateFilter {
            get {
                return ResourceManager.GetString("HistoryView_FromDateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj Upo jako PDF.
        /// </summary>
        public static string HistoryView_GenerateUpoAsPDFBtn {
            get {
                return ResourceManager.GetString("HistoryView_GenerateUpoAsPDFBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr referencyjny.
        /// </summary>
        public static string HistoryView_RefNoHeader {
            get {
                return ResourceManager.GetString("HistoryView_RefNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odśwież statusy.
        /// </summary>
        public static string HistoryView_RefreshStatusBtn {
            get {
                return ResourceManager.GetString("HistoryView_RefreshStatusBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz Upo jako XML.
        /// </summary>
        public static string HistoryView_SaveUpoAsXmlBtn {
            get {
                return ResourceManager.GetString("HistoryView_SaveUpoAsXmlBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wysyłki.
        /// </summary>
        public static string HistoryView_SendDateHeader {
            get {
                return ResourceManager.GetString("HistoryView_SendDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwer.
        /// </summary>
        public static string HistoryView_ServerTypeHeader {
            get {
                return ResourceManager.GetString("HistoryView_ServerTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string HistoryView_StatusHeader {
            get {
                return ResourceManager.GetString("HistoryView_StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia zapytań.
        /// </summary>
        public static string HistoryView_Title {
            get {
                return ResourceManager.GetString("HistoryView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do:.
        /// </summary>
        public static string HistoryView_ToDateFilter {
            get {
                return ResourceManager.GetString("HistoryView_ToDateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upo.
        /// </summary>
        public static string HistoryView_UpoHeader {
            get {
                return ResourceManager.GetString("HistoryView_UpoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MainView_CheckStatusBtn {
            get {
                return ResourceManager.GetString("MainView_CheckStatusBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść okno logu.
        /// </summary>
        public static string MainView_ClearLogViewToolTip {
            get {
                return ResourceManager.GetString("MainView_ClearLogViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string MainView_EditBtn {
            get {
                return ResourceManager.GetString("MainView_EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wyjście.
        /// </summary>
        public static string MainView_FileExitMenuItem {
            get {
                return ResourceManager.GetString("MainView_FileExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Plik.
        /// </summary>
        public static string MainView_FileMenuItem {
            get {
                return ResourceManager.GetString("MainView_FileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Historia.
        /// </summary>
        public static string MainView_HistoryMenuItem {
            get {
                return ResourceManager.GetString("MainView_HistoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik wejściowy:.
        /// </summary>
        public static string MainView_InputFileLabel {
            get {
                return ResourceManager.GetString("MainView_InputFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr referencyjny:.
        /// </summary>
        public static string MainView_RefNoLabel {
            get {
                return ResourceManager.GetString("MainView_RefNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Usuń zapiane ustawienia list w edycji.
        /// </summary>
        public static string MainView_ResetEditSettingsMenuItem {
            get {
                return ResourceManager.GetString("MainView_ResetEditSettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz log.
        /// </summary>
        public static string MainView_SaveLogViewToolTip {
            get {
                return ResourceManager.GetString("MainView_SaveLogViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string MainView_SendBtn {
            get {
                return ResourceManager.GetString("MainView_SendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij bez walidacji.
        /// </summary>
        public static string MainView_SendNoValidationBtn {
            get {
                return ResourceManager.GetString("MainView_SendNoValidationBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Serwer.
        /// </summary>
        public static string MainView_ServerMenuItem {
            get {
                return ResourceManager.GetString("MainView_ServerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Produkcyjny.
        /// </summary>
        public static string MainView_ServerProductionMenuItem {
            get {
                return ResourceManager.GetString("MainView_ServerProductionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Testowy.
        /// </summary>
        public static string MainView_ServerTestMenuItem {
            get {
                return ResourceManager.GetString("MainView_ServerTestMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Konfiguracja.
        /// </summary>
        public static string MainView_SettingsConfigurationMenuItem {
            get {
                return ResourceManager.GetString("MainView_SettingsConfigurationMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ustawienia.
        /// </summary>
        public static string MainView_SettingsMenuItem {
            get {
                return ResourceManager.GetString("MainView_SettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane użytkownika.
        /// </summary>
        public static string MainView_UserDataTitle {
            get {
                return ResourceManager.GetString("MainView_UserDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waliduj.
        /// </summary>
        public static string MainView_ValidateBtn {
            get {
                return ResourceManager.GetString("MainView_ValidateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walidacja pliku zakończona. Wystąpiły błędy przy walidacji..
        /// </summary>
        public static string MainView_ValidationEndedErrorsTxt {
            get {
                return ResourceManager.GetString("MainView_ValidationEndedErrorsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walidacja pliku zakończona. Plik prawidłowy..
        /// </summary>
        public static string MainView_ValidationEndedOkTxt {
            get {
                return ResourceManager.GetString("MainView_ValidationEndedOkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walidacja pliku w toku....
        /// </summary>
        public static string MainView_ValidationStartedTxt {
            get {
                return ResourceManager.GetString("MainView_ValidationStartedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wersja aplikacji.
        /// </summary>
        public static string MainView_VersionMenuItem {
            get {
                return ResourceManager.GetString("MainView_VersionMenuItem", resourceCulture);
            }
        }
    }
}
